os: Visual Studio 2017
configuration: Release
clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  CAKE_SETTINGS_SKIPVERIFICATION: true
  ANDROID_HOME: 'C:\Program Files (x86)\Android\android-sdk\'  
  
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(appveyor_build_version)

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)

install:
- ps: Invoke-WebRequest https://cakebuild.net/download/bootstrapper/windows -OutFile build.ps1    
# - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

build_script:
- ps: .\build.ps1 -Target Default -Verbosity Diagnostic

test_script: 
 cmd: dotnet test source\Tests\FFImageLoading.Tests -c Release --no-build --no-restore

artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
